server {
  listen 80;
  server_name _;

  if ($host = "eldoo.in") {
    return 301 https://www.eldoo.in$request_uri;
  }

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /env-config.js {
    add_header Cache-Control "no-store";
  }
}
