services:
  - type: web
    name: voltmart-backend
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        sync: false
      - key: APP_SEED_ADMIN_EMAIL
        sync: false
      - key: APP_SEED_ADMIN_PASSWORD
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://www.eldoo.in,https://eldoo.in,https://voltmart-frontend.onrender.com
      - key: APP_STORE_FRONTEND_URL
        value: https://www.eldoo.in
      - key: APP_GOOGLE_CLIENT_ID
        value: 536121505527-9vfs7pm13jjrvsb9np95nubbpji6b01l.apps.googleusercontent.com
      - key: APP_EMAIL_ENABLED
        value: "true"
      - key: APP_EMAIL_PROVIDER
        value: brevo
      - key: APP_EMAIL_FROM_ADDRESS
        sync: false
      - key: APP_EMAIL_FROM_NAME
        value: VoltMart
      - key: APP_EMAIL_API_KEY
        sync: false
      - key: APP_EMAIL_API_URL
        value: https://api.brevo.com/v3/smtp/email
      - key: APP_MSG91_ENABLED
        value: "true"
      - key: APP_MSG91_AUTH_KEY
        sync: false
      - key: APP_MSG91_TEMPLATE_ID
        sync: false
      - key: APP_MSG91_SENDER_ID
        sync: false
      - key: APP_MSG91_COUNTRY_CODE
        value: "91"
      - key: APP_MSG91_BASE_URL
        value: https://control.msg91.com

  - type: web
    name: voltmart-frontend
    env: docker
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://voltmart-backend-xuho.onrender.com/api
      - key: REACT_APP_GOOGLE_CLIENT_ID
        value: 536121505527-9vfs7pm13jjrvsb9np95nubbpji6b01l.apps.googleusercontent.com
      - key: REACT_APP_MSG91_WIDGET_ID
        sync: false
      - key: REACT_APP_MSG91_TOKEN_AUTH
        sync: false
